### ISSUE TITLE
pulling resources from cli stopped working

### ISSUE THREAD

**Issue by mchimirev** [mbryzek/apidoc-cli#3]
For example:

http://apidoc.me/gilt/api-user-registration/0.0.2/play_2_x_routes used to return contents of the routes file, and with it this command...

```
$ /web/apidoc-cli/bin/apidoc code gilt api-user-registration 0.0.2 play_2_x_routes
```

... used to pull contents of routes. 

But now that generators could contain multiple files, routes live at:  http://apidoc.me/gilt/api-user-registration/0.0.2/play_2_x_routes/routes

and, seemingly, with this change cli command returns a listing of files

```
$ /web/apidoc-cli/bin/apidoc code gilt api-user-registration 0.0.2 play_2_x_routes
play_2_x_routes Files:
 - routes
```

**Comment by mchimirev** [comment]
Actually, this command (for example) does the job, closing ticket!!!

/web/apidoc-cli/bin/apidoc code gilt api-user-registration 0.0.3 play_2_x_json GiltApiUserRegistrationV0Models.scala > app/com/gilt/api/user/registration/v0/models/Apidoc.scala

above will pull the file "GiltApiUserRegistrationV0Models.scala" from generator "play_2_x_json"

**Comment by mchimirev** [comment]
Still need a way to download a zip file, for example from here: http://apidoc.me/gilt/checkout-api/latest/android_client  (generator takes ~2 minutes to warm up on lambda, so if you get an error on that page - try again after ~2 minutes)

**Comment by mbryzek** [comment]
Moving here to track as feature: https://github.com/mbryzek/apidoc-cli/issues/13
